### ISSUE TITLE
Incompatible with google-cloud-bigquery-storage>=2.0.0

### ISSUE THREAD

**Issue by andrewbrown248** [pydata/pandas-gbq#329]
In the 2.0.0 version of google-cloud-bigquery-storage, they dropped the bigquery_storage_v1beta1 module for just bigquery_storage.  This causes the following line to fail importing with google-cloud-bigquery-storage>=2.0.0.

https://github.com/pydata/pandas-gbq/blob/d251db03b159447331ac9ae63e13d295d75bad70/pandas_gbq/gbq.py#L20

Later, when trying to use the storage api, the following error is thrown since the module was unable to be imported.  
```
ImportError: Install the google-cloud-bigquery-storage and fastavro/pyarrow packages to use the BigQuery Storage API.
```

Dropped bigquery_storage_v1beta1 module:
```
(env) abrown:~$ pip list | grep google-cloud-bigquery-storage
google-cloud-bigquery-storage  2.0.0    
(env) abrown:~$ python
Python 3.7.9 (default, Aug 27 2020, 21:59:41) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import bigquery_storage_v1beta1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'bigquery_storage_v1beta1' from 'google.cloud' (unknown location)
>>> from google.cloud import bigquery_storage
>>>
```

**Comment by tswast** [comment]
Thank you for the report! The temporary fix is probably to release a patch release with the correct top bound dependencies in `setup.py`.

Long term, it'll make sense to ensure it works with the 2.0 package, as that's where improvements will be made.

**Comment by tswast** [comment]
Looks like we don't actually define `google-cloud-bigquery-storage` as a dependency in `setup.py` (even though it's needed for best performance). I'll check the [pandas-gbq conda feedstock](https://github.com/conda-forge/pandas-gbq-feedstock) and make sure we define a maximum version there.

**Comment by tswast** [comment]
It's also not defined in the feedstock (perhaps something to update), but is set to limit to less than 2.0dev in  google-cloud-bigquery

https://github.com/conda-forge/google-cloud-bigquery-feedstock/blob/3bf0d97f7e88c01b66421768183b7bf3b8ed7842/recipe/meta.yaml#L119
